version: '2.1'
services:
  web:
    build: .
    container_name: go-app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=godb
      - DB_PORT=3306
    networks:
      - mynet
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    container_name: godb
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    security_opt:
      - seccomp:unconfined
    networks:
      - mynet
  #ZAP - DAST Scanner by OWASP. You can disable it if you want
  zaproxy:
    image: owasp/zap2docker-stable
    command: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.\* -config api.addrs.addr.regex=true
    ports:
      - 8090:8090
    expose:
      - "8090"
    container_name: zaproxy
    networks:
      - mynet
  #Arachni - DAST Scanner by Tasos Laskos. You can disable it if you want
  arachni:
    image: ahannigan/docker-arachni
    command: bin/arachni_rest_server --address 0.0.0.0
    ports:
      - 7331:731
    expose:
      - "7331"
    networks:
      - mynet
    container_name: arachni
networks:
  mynet:
    driver: "bridge"