version: '2.1'
services:
  web:
    build: .
    container_name: go-app
    ports:
      - 8080:8080
    networks:
      - mynet
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    container_name: godb
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - mynet
  #ZAP - DAST Scanner by OWASP. You can disable it if you want
  zaproxy:
    image: owasp/zap2docker-stable
    command: zap.sh -daemon -port 8090 -host 0.0.0.0
    expose:
      - "8090"
    networks:
      - mynet
  #Arachni - DAST Scanner by Tasos Laskos. You can disable it if you want
  arachni:
    image: arachni/arachni
    ports:
      - 7331:7331
    networks:
      - mynet
networks:
  mynet:
    driver: "bridge"